### ISSUE TITLE
Words not getting highlighted properly

### ISSUE THREAD

**Issue by tanmayrajani** [pd4d10/octohint#23]
- There seems to be a shift of one character when I tried to highlight a word today. Interesting thing is, it's not happening for every word in the file. I tried disabling every other extension and this still persists. Following is the screenshot of such occurance: [(file in the image below)](https://github.com/sindresorhus/ky/blob/master/index.js)
![image](https://user-images.githubusercontent.com/8295888/45253370-a5e2ec00-b383-11e8-974e-a02e018e0450.png)
   

- Apart from that, when I tried it with [refined-github](https://github.com/sindresorhus/refined-github) enabled, I got the following behaviour. I think it's because of the feature: [Tabs are shown as 4 spaces instead of 8](https://cloud.githubusercontent.com/assets/170270/14170088/d3be931e-f755-11e5-8edf-c5f864336382.png) (I'm not able to find which file does that in RGH so I couldn't disable that feature and test)
![image](https://user-images.githubusercontent.com/8295888/45253360-8055e280-b383-11e8-9d37-44bf350e18d1.png)

**Comment by pd4d10** [comment]
Thanks for your report.

* Seems GitHub's first tab indent is 7, not 8. I don't know if it is a bug or by design. Already submit it to https://github.com/contact.

* Currently GitHub determines tab size by checking project's `.editorconfig`. Octohint follows it. In this case, it seems more reasonable to determine tab size by page content already rendered, since other extensions or user scripts may change the default behavior

**Comment by pd4d10** [comment]
@tanmayrajani Tab size is compatible with refined-github at v2.0.6, which is already published to Chrome Web Store. Should be auto updated soon.

The first issue is confirmed by GitHub Team. They are working on it.

**Comment by tanmayrajani** [comment]
Thank you for the quick implementation. Just verified the fix with Refined GitHub. I'll go ahead and close this issue now since the remaining part is from GitHub itself. Cheers! :)
