### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by pexcn** [pd4d10/octohint#3]
Such as C, Java, C++..., Do you have a plan to support their?

**Comment by pd4d10** [comment]
@pexcn v1.5.0 support all languages.

Octohint is a pure client thing, we can only use JavaScript to do code analysis. since there is no JS libs to do AST parsing for C, Java or C++ code, only basic token match is supported. Means that if you click a variable named `foo`, it will find all `foo`, just string matching.

Not that smart, but I hope it will be helpful.

Thanks!

**Comment by pexcn** [comment]
Thanks a lot~
