### ISSUE TITLE
Marked as unsafe and removed from the Chrome webstore

### ISSUE THREAD

**Issue by aminya** [pd4d10/octohint#37]
This extension is marked as unsafe and removed from the chrome webstore.

The link no longer works.
https://chrome.google.com/webstore/detail/octohint/hbkpjkfdheainjkkebeoofkpgddnnbpk

**Comment by lewisje** [comment]
I'm not sure about whether it really is unsafe, but I know that when I browsed the code for the version of Octohint that I still had (which FWIW is later than the version in this repo, 2.0.8 instead of 2.0.7), I found a lot of packing and obfuscation (most of it related to the module loader and the compilation of TypeScript); maybe I'll upload an archive if and when I'm satisfied that Google made a false positive, but for now, https://github.com/stefanbuck/awesome-browser-extensions-for-github recommends an alternative, albeit one with more features than just code-hinting: https://github.com/sourcegraph/sourcegraph

**Comment by pd4d10** [comment]
Resubmitted, waiting for the review. Thanks for your report!

It was removed by Chrome Web Store because some new fields need to be filled in, while I didn't respond in time. Actually, nothing to do with 'unsafe'.

**Comment by pd4d10** [comment]
Published as v2.0.9
